const characters = [
	{
		id: 1,
		name: 'Harry Potter',
		alternate_names: [
			'The Boy Who Lived',
			'The Chosen One',
			'Undesirable No. 1',
			'Potty',
		],
		species: 'human',
		gender: 'male',
		house: 'Gryffindor',
		dateOfBirth: '31-07-1980',
		yearOfBirth: 1980,
		wizard: true,
		ancestry: 'half-blood',
		eyeColour: 'green',
		hairColour: 'black',
		wand: {
			wood: 'holly',
			core: 'phoenix tail feather',
			length: 11,
		},
		patronus: 'stag',
		hogwartsStudent: true,
		hogwartsStaff: false,
		actor: 'Daniel Radcliffe',
		alternate_actors: [],
		alive: true,
		image: require('../assets/characters/harry.jpg'),
	},
	{
		id: 2,
		name: 'Hermione Granger',
		alternate_names: ['Hermy', 'Know-it-all', 'Miss Grant', 'Herm-own-ninny'],
		species: 'human',
		gender: 'female',
		house: 'Gryffindor',
		dateOfBirth: '19-09-1979',
		yearOfBirth: 1979,
		wizard: true,
		ancestry: 'muggleborn',
		eyeColour: 'brown',
		hairColour: 'brown',
		wand: {
			wood: 'vine',
			core: 'dragon heartstring',
			length: 10.75,
		},
		patronus: 'otter',
		hogwartsStudent: true,
		hogwartsStaff: false,
		actor: 'Emma Watson',
		alternate_actors: [],
		alive: true,
		image: require('../assets/characters/hermione.jpg'),
	},
	{
		id: 3,
		name: 'Ron Weasley',
		alternate_names: [
			'Dragomir Despard',
			'Ronald',
			'Ickle Ronniekins',
			'Ronnie',
			'Wheezy',
			'Won-Won',
			'Roonil Wazlib',
		],
		species: 'human',
		gender: 'male',
		house: 'Gryffindor',
		dateOfBirth: '01-03-1980',
		yearOfBirth: 1980,
		wizard: true,
		ancestry: 'pure-blood',
		eyeColour: 'blue',
		hairColour: 'red',
		wand: {
			wood: 'willow',
			core: 'unicorn tail hair',
			length: 14,
		},
		patronus: 'Jack Russell terrier',
		hogwartsStudent: true,
		hogwartsStaff: false,
		actor: 'Rupert Grint',
		alternate_actors: [],
		alive: true,
		image: require('../assets/characters/ron.jpg'),
	},
	{
		id: 4,
		name: 'Lord Voldemort',
		alternate_names: [
			'Tom Riddle',
			'Tom Marvolo Riddle',
			'You-Know-Who',
			'He Who Must Not Be Named',
			'the Dark Lord',
			'the Heir of Slytherin',
		],
		species: 'human',
		gender: 'male',
		house: 'Slytherin',
		dateOfBirth: '31-12-1926',
		yearOfBirth: 1926,
		wizard: true,
		ancestry: 'half-blood',
		eyeColour: 'Scarlet',
		hairColour: 'bald',
		wand: {
			wood: 'yew',
			core: 'phoenix tail feather',
			length: 13.5,
		},
		patronus: '',
		hogwartsStudent: false,
		hogwartsStaff: false,
		actor: 'Ralph Fiennes',
		alternate_actors: [],
		alive: false,
		image: require('../assets/characters/voldemort.jpg'),
	},
	{
		id: 5,
		name: 'Severus Snape',
		alternate_names: ['Half-Blood Prince', 'Snivellus', 'Sev'],
		species: 'human',
		gender: 'male',
		house: 'Slytherin',
		dateOfBirth: '09-01-1960',
		yearOfBirth: 1960,
		wizard: true,
		ancestry: 'half-blood',
		eyeColour: 'black',
		hairColour: 'black',
		wand: {
			wood: '',
			core: '',
			length: null,
		},
		patronus: 'doe',
		hogwartsStudent: false,
		hogwartsStaff: true,
		actor: 'Alan Rickman',
		alternate_actors: [],
		alive: false,
		image: require('../assets/characters/severus.jpg'),
	},
	{
		id: 6,
		name: 'Albus Dumbledore',
		alternate_names: ['Professor Dumbledore'],
		species: 'human',
		gender: 'male',
		house: 'Gryffindor',
		dateOfBirth: null,
		yearOfBirth: 1881,
		wizard: true,
		ancestry: 'half-blood',
		eyeColour: 'blue',
		hairColour: 'silver',
		wand: {
			wood: '',
			core: '',
			length: null,
		},
		patronus: 'Phoenix',
		hogwartsStudent: false,
		hogwartsStaff: true,
		actor: 'Richard Harris',
		alternate_actors: ['Michael Gambon'],
		alive: false,
		image: require('../assets/characters/dumbledore.jpg'),
	},
	{
		id: 7,
		name: 'Draco Malfoy',
		alternate_names: [],
		species: 'human',
		gender: 'male',
		house: 'Slytherin',
		dateOfBirth: '05-06-1980',
		yearOfBirth: 1980,
		wizard: true,
		ancestry: 'pure-blood',
		eyeColour: 'grey',
		hairColour: 'blonde',
		wand: {
			wood: 'hawthorn',
			core: 'unicorn tail hair',
			length: 10,
		},
		patronus: '',
		hogwartsStudent: true,
		hogwartsStaff: false,
		actor: 'Tom Felton',
		alternate_actors: [],
		alive: true,
		image: require('../assets/characters/malfoy.jpg'),
	},
	{
		id: 8,
		name: 'Neville Longbottom',
		alternate_names: [],
		species: 'human',
		gender: 'male',
		house: 'Gryffindor',
		dateOfBirth: '30-07-1980',
		yearOfBirth: 1980,
		wizard: true,
		ancestry: 'pure-blood',
		eyeColour: '',
		hairColour: 'blonde',
		wand: {
			wood: 'cherry',
			core: 'unicorn tail hair',
			length: 13,
		},
		patronus: 'Non-Corporeal',
		hogwartsStudent: true,
		hogwartsStaff: false,
		actor: 'Matthew Lewis',
		alternate_actors: [],
		alive: true,
		image: require('../assets/characters/neville.jpg'),
	},
	{
		id: 9,
		name: 'Minerva McGonagall',
		alternate_names: [],
		species: 'human',
		gender: 'female',
		house: 'Gryffindor',
		dateOfBirth: '04-10-1925',
		yearOfBirth: 1925,
		wizard: true,
		ancestry: 'half-blood',
		eyeColour: '',
		hairColour: 'black',
		wand: {
			wood: 'fir',
			core: 'dragon heartstring',
			length: 9.5,
		},
		patronus: 'tabby cat',
		hogwartsStudent: false,
		hogwartsStaff: true,
		actor: 'Dame Maggie Smith',
		alternate_actors: [],
		alive: true,
		image: require('../assets/characters/minerva.jpg'),
	},
	{
		id: 10,
		name: 'Rubeus Hagrid',
		alternate_names: ['Professor Hagrid', 'Hagger'],
		species: 'half-giant',
		gender: 'male',
		house: 'Gryffindor',
		dateOfBirth: '06-12-1928',
		yearOfBirth: 1928,
		wizard: true,
		ancestry: 'half-blood',
		eyeColour: 'black',
		hairColour: 'black',
		wand: {
			wood: 'oak',
			core: '',
			length: 16,
		},
		patronus: '',
		hogwartsStudent: false,
		hogwartsStaff: true,
		actor: 'Robbie Coltrane',
		alternate_actors: [],
		alive: true,
		image: require('../assets/characters/hagrid.jpg'),
	},
	{
		id: 11,
		name: 'Luna Lovegood',
		alternate_names: ['Loony Lovegood'],
		species: 'human',
		gender: 'female',
		house: 'Ravenclaw',
		dateOfBirth: '13-02-1981',
		yearOfBirth: 1981,
		wizard: true,
		ancestry: '',
		eyeColour: 'silver',
		hairColour: 'blonde',
		wand: {
			wood: '',
			core: '',
			length: null,
		},
		patronus: 'hare',
		hogwartsStudent: true,
		hogwartsStaff: false,
		actor: 'Evanna Lynch',
		alternate_actors: [],
		alive: true,
		image: require('../assets/characters/luna.jpg'),
	},
	{
		id: 12,
		name: 'Ginny Weasley',
		alternate_names: [],
		species: 'human',
		gender: 'female',
		house: 'Gryffindor',
		dateOfBirth: '11-08-1981',
		yearOfBirth: 1981,
		wizard: true,
		ancestry: 'pure-blood',
		eyeColour: 'brown',
		hairColour: 'red',
		wand: {
			wood: 'yew',
			core: '',
			length: null,
		},
		patronus: 'horse',
		hogwartsStudent: true,
		hogwartsStaff: false,
		actor: 'Bonnie Wright',
		alternate_actors: [],
		alive: true,
		image: require('../assets/characters/ginny.jpg'),
	},
	{
		id: 13,
		name: 'Bellatrix Lestrange',
		alternate_names: ['Bella'],
		species: 'human',
		gender: 'female',
		house: 'Slytherin',
		dateOfBirth: null,
		yearOfBirth: 1951,
		wizard: true,
		ancestry: 'pure-blood',
		eyeColour: 'brown',
		hairColour: 'black',
		wand: {
			wood: 'walnut',
			core: 'dragon heartstring',
			length: 12.75,
		},
		patronus: '',
		hogwartsStudent: false,
		hogwartsStaff: false,
		actor: 'Helena Bonham Carter',
		alternate_actors: [],
		alive: false,
		image: require('../assets/characters/bellatrix.jpg'),
	},
];
export default class Api {
	static async getCharacters() {
		const data = {
			code: 200,
			status: 'Ok',
			copyright: '© 2024 HOGWARTS',
			attributionText: 'Data provided by Hogwarts. © 2024 HOGWARTS',
			attributionHTML:
				'<a href="https://hp-api.onrender.com">Data provided by Hogwarts. © 2024 HOGWARTS</a>',
			etag: 'f069fc571b245cfbdd2a168a05d611fcdaeb4f71',
			data: {
				offset: 0,
				limit: 20,
				total: 1564,
				count: 20,
				results: characters.map((character) => ({
					id: character.id,
					name: character.name,
					house: character.house,
					description: `${character.species}
      - ${character.gender}
      - ${character.house}
      - ${character.wand.wood}
      - ${character.wand.core}
      - ${character.wand.length}`,
					thumbnail: {
						path: character.image,
						extension: 'jpg',
					},
					alternate_names: character.alternate_names?.join(', '),
				})),
			},
		};
		return data;
	}

	static async getCharacter(id) {
		const data = {
			code: 200,
			status: 'Ok',
			copyright: '© 2024 HOGWARTS',
			attributionText: 'Data provided by Hogwarts. © 2024 HOGWARTS',
			attributionHTML:
				'<a href="https://hp-api.onrender.com">Data provided by Hogwarts. © 2024 HOGWARTS</a>',
			etag: 'f069fc571b245cfbdd2a168a05d611fcdaeb4f71',
			data: {
				offset: 0,
				limit: 20,
				total: 1564,
				count: 20,
				results: characters
					.filter((char) => char.id == id)
					.map((character) => ({
						id: character.id,
						name: character.name,
						house: character.house,
						description: `${character.species}
      - ${character.gender}
      - ${character.house}
      - ${character.wand.wood}
      - ${character.wand.core}
      - ${character.wand.length}`,
						thumbnail: {
							path: character.image,
							extension: 'jpg',
						},
						alternate_names: character.alternate_names?.map(
							(name) => `${name}, `
						),
					})),
			},
		};

		return data;
	}
}
